# Generated by Django 4.2.7 on 2025-12-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_clinic__a438a5_idx',
            old_name='accounts_no_clinic__2fcf95_idx',
        ),
    ]
