"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.
"""

import os
from datetime import timedelta
from decimal import Decimal
from pathlib import Path
from typing import List

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present.
load_dotenv(BASE_DIR / ".env", override=False)


def get_env(name: str, default: str | None = None) -> str:
    """Read environment variable or raise when missing and no default given."""
    value = os.getenv(name, default)
    if value is None:
        raise ImproperlyConfigured(f"Missing environment variable: {name}")
    return value


def get_bool_env(name: str, default: bool = False) -> bool:
    """Interpret boolean-ish environment variables."""
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.lower() in {"1", "true", "yes", "on"}


def get_list_env(name: str, default: List[str] | None = None) -> List[str]:
    """Return comma-separated environment variable as list."""
    raw = os.getenv(name)
    if raw is None:
        return default or []
    return [item.strip() for item in raw.split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env("DJANGO_SECRET_KEY", "local-insecure-secret")
ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY", "local-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = get_list_env("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "pgvector.django",
    "apps.common",
    "apps.clinics",
    "apps.patients",
    "apps.appointments",
    "apps.conversations",
    "apps.templates",
    "apps.kb",
    "apps.channels",
    "apps.calendars",
    "apps.dialog",
    "apps.llm",
    "apps.webhooks",
    "apps.http_api",
    "apps.workers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# Prefer Postgres, fallback to SQLite for local dev without env configuration.

if os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": get_env("POSTGRES_DB"),
            "USER": get_env("POSTGRES_USER"),
            "PASSWORD": get_env("POSTGRES_PASSWORD"),
            "HOST": get_env("POSTGRES_HOST", "localhost"),
            "PORT": get_env("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
    ("ar", "Arabic"),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Outbound integrations (WhatsApp, Google, LLMs)

WHATSAPP_DEFAULT_SENDER = os.getenv("WHATSAPP_DEFAULT_SENDER", "")
LEAD_WEBHOOK_SECRET = get_env("LEAD_WEBHOOK_SECRET", "local-secret")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI", "")

DEEPSEEK_API_BASE = os.getenv("DEEPSEEK_API_BASE", "https://api.deepseek.com")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")

LLM_TIMEOUT_SECONDS = int(os.getenv("LLM_TIMEOUT_SECONDS", "15"))
LLM_DEFAULT_MODEL = os.getenv("LLM_DEFAULT_MODEL", "deepseek-chat")
RAG_INDEX_NAME = os.getenv("RAG_INDEX_NAME", "default")
RAG_TOP_K = int(os.getenv("RAG_TOP_K", "4"))
LLM_MAX_LATENCY_MS = int(os.getenv("LLM_MAX_LATENCY_MS", "12000"))
LLM_COST_BUDGET_PER_DAY = Decimal(os.getenv("LLM_COST_BUDGET_PER_DAY", "0"))
LLM_COST_PER_REQUEST = Decimal(os.getenv("LLM_COST_PER_REQUEST", "0.002"))
LLM_FALLBACK_TEMPLATE_NAME = os.getenv("LLM_FALLBACK_TEMPLATE_NAME", "session_clarify")
RAG_MAX_TOKENS = int(os.getenv("RAG_MAX_TOKENS", "1000"))
RAG_CHARS_PER_TOKEN = int(os.getenv("RAG_CHARS_PER_TOKEN", "4"))
WHATSAPP_SESSION_FALLBACK_HSM_NAME = os.getenv("WHATSAPP_SESSION_FALLBACK_HSM_NAME", "session_clarify")
DATA_RETENTION_DAYS = int(os.getenv("DATA_RETENTION_DAYS", "30"))


# Celery / Worker defaults

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)

REMINDER_LEAD_TIME = {
    "plus_24h": timedelta(hours=24),
    "plus_2h": timedelta(hours=2),
}


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
