# Generated by Django 4.2.7 on 2025-10-23 19:40

from django.db import migrations, models
from apps.common.fields import CompatArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='tags',
            field=CompatArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
    ]
