# Generated by Django 4.2.7 on 2025-12-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dialog", "0001_initial"),
        ("conversations", "0002_increase_language_field_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogTurnLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("intent_predicted", models.CharField(blank=True, max_length=100)),
                ("intent_confidence", models.FloatField(default=0)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("handoff_reason", models.CharField(blank=True, max_length=100)),
                ("validator_fail_reason", models.CharField(blank=True, max_length=100)),
                ("llm_calls", models.PositiveIntegerField(default=0)),
                ("llm_tokens", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="turn_logs", to="conversations.conversation")),
                ("message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="turn_logs", to="conversations.conversationmessage")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
