# Generated by Django 4.2.7 on 2025-10-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_webhooks', to='clinics.clinic')),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_webhook_events', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
