# Generated by Django 4.2.7 on 2025-10-22 21:05

from django.db import migrations, models
import django.db.models.deletion
from apps.common.fields import CompatArrayField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('phone_number', models.CharField(max_length=32)),
                ('normalized_phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tags', CompatArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('clinic', 'normalized_phone')},
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
