# Generated by Django 4.2.7 on 2025-10-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('provider_template_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['clinic_id', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='outboxmessage',
            name='template_code',
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='message_type',
            field=models.CharField(choices=[('session', 'Session'), ('hsm', 'HSM')], default='hsm', max_length=10),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='outboxmessage',
            index=models.Index(fields=['idempotency_key'], name='channels_ou_idempot_9fbfc2_idx'),
        ),
        migrations.AddField(
            model_name='hsmtemplate',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hsm_templates', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='hsm_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_messages', to='channels.hsmtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='hsmtemplate',
            unique_together={('clinic', 'name', 'language')},
        ),
    ]
