# Generated by Django 4.2.7 on 2025-12-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_hsmtemplate_remove_outboxmessage_template_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsmtemplate',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('en_US', 'English (US)')], default='en', max_length=5),
        ),
    ]
