# Generated by Django 4.2.7 on 2025-10-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('fallback', 'Fallback')], default='deepseek', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to='kb.knowledgechunk')),
                ('conversation_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='conversations.conversationmessage')),
                ('llm_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to='llm.llmrequestlog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
