# Generated by Django 4.2.7 on 2025-10-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrequestlog',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
