# Generated by Django 4.2.7 on 2025-11-08 22:28

import apps.common.fields
import django.contrib.postgres.constraints
from django.db import migrations, models
from django.contrib.postgres.constraints import ExclusionConstraint



class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="slot",
            field=apps.common.fields.CompatDateTimeRangeField(),
        ),
        # إسقاط القيد على مستوى قاعدة البيانات فقط (إن وُجد) دون لمس state
        migrations.RunSQL(
            sql='ALTER TABLE "appointments_appointment" '
                'DROP CONSTRAINT IF EXISTS prevent_double_booking;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        # إعادة تعريف القيد بشكل رسمي في الـstate + DB
        migrations.AddConstraint(
            model_name="appointment",
            constraint=ExclusionConstraint(
                name="prevent_double_booking",
                expressions=[("clinic", "="), ("slot", "&&")],
                condition=models.Q(("status", "booked")),
            ),
        ),
    ]